### ISSUE TITLE
Stack Trace

### ISSUE THREAD

**Issue by DenDog1** [otakuhqz/ZimLX#16]
Build version: 0.4.4 
Build date: 1979-11-29 16:00:00 
Current date: 2019-02-07 22:16:21 
Device: Samsung SM-N960U 
 
Stack trace:  
java.lang.IllegalArgumentException: Receiver not registered: org.zimmob.zimlx.overlay.LauncherClientImpl$updateReceiver$1@20af10e
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1338)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1583)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:672)
	at org.zimmob.zimlx.overlay.LauncherClientImpl.removeClient(LauncherClientImpl.kt:108)
	at org.zimmob.zimlx.overlay.LauncherClientImpl.remove(LauncherClientImpl.kt:184)
	at org.zimmob.zimlx.settings.Settings.onSharedPreferenceChanged(Settings.java:133)
	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:607)
	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:489)
	at android.support.v7.preference.Preference.tryCommit(Preference.java:1545)
	at android.support.v7.preference.Preference.persistBoolean(Preference.java:1848)
	at android.support.v7.preference.TwoStatePreference.setChecked(TwoStatePreference.java:82)
	at android.support.v7.preference.TwoStatePreference.onClick(TwoStatePreference.java:67)
	at android.support.v7.preference.Preference.performClick(Preference.java:1114)
	at android.support.v7.preference.Preference.performClick(Preference.java:1099)
	at android.support.v14.preference.SwitchPreference.performClick(SwitchPreference.java:212)
	at android.support.v7.preference.Preference$1.onClick(Preference.java:169)
	at android.view.View.performClick(View.java:7333)
	at android.view.View.performClickInternal(View.java:7299)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27774)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by otakuhqz** [comment]
fixed on v0.5
