### ISSUE TITLE
Crash at startup after update

### ISSUE THREAD

**Issue by nartahn** [otakuhqz/ZimLX#53]
**Describe the bug**
After I updated the app no longer works.

**To Reproduce**
1. Update
2. open app
3. after crash, restart app
4. goto 3.
5. See error

**Error Message**

Build version: 0.6.2b 
Build date: 1979-11-30 11:00:00 
Current date: 2019-06-19 20:52:54 
Device: LGE Maru on the Nexus 5 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.zimmob.zimlx/org.zimmob.zimlx.ZimLauncher}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:273)
	at org.zimmob.zimlx.ZimPreferences$IntPref.onGetValue(ZimPreferences.kt:452)
	at org.zimmob.zimlx.ZimPreferences$IntPref.onGetValue(ZimPreferences.kt:450)
	at org.zimmob.zimlx.ZimPreferences$PrefDelegate.getValue(ZimPreferences.kt:545)
	at org.zimmob.zimlx.settings.GridSize.getNumRowsPref(Unknown Source:7)
	at org.zimmob.zimlx.settings.GridSize.applyNumRows(GridSize.kt:31)
	at org.zimmob.zimlx.settings.GridSize.<init>(GridSize.kt:23)
	at org.zimmob.zimlx.ZimPreferences$dockGridSizeDelegate$1.invoke(ZimPreferences.kt:94)
	at org.zimmob.zimlx.ZimPreferences$dockGridSizeDelegate$1.invoke(ZimPreferences.kt:32)
	at org.zimmob.zimlx.ZimPreferences$ResettableLazy.getValue(ZimPreferences.kt:595)
	at org.zimmob.zimlx.ZimPreferences.getDockGridSize(Unknown Source:8)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:328)
	at com.google.android.apps.nexuslauncher.NexusLauncherActivity.onCreate(NexusLauncherActivity.java:27)
	at org.zimmob.zimlx.ZimLauncher.onCreate(ZimLauncher.java:57)
	at android.app.Activity.performCreate(Activity.java:7009)
	at android.app.Activity.performCreate(Activity.java:7000)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
	... 9 more

**Comment by TheDcoder** [comment]
Experiencing the same issue on my 2 phones as well, one of them doesn't even give me the crash screen.

```
Build version: 0.6.2b 
Build date: 1979-11-30 05:30:00 
Current date: 2019-06-20 07:27:33 
Device: Lenovo Lenovo K8 Note 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.zimmob.zimlx/org.zimmob.zimlx.ZimLauncher}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2904)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2986)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:6784)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:272)
	at org.zimmob.zimlx.ZimPreferences$IntPref.onGetValue(ZimPreferences.kt:452)
	at org.zimmob.zimlx.ZimPreferences$IntPref.onGetValue(ZimPreferences.kt:450)
	at org.zimmob.zimlx.ZimPreferences$PrefDelegate.getValue(ZimPreferences.kt:545)
	at org.zimmob.zimlx.settings.GridSize.getNumRowsPref(Unknown Source:7)
	at org.zimmob.zimlx.settings.GridSize.applyNumRows(GridSize.kt:31)
	at org.zimmob.zimlx.settings.GridSize.<init>(GridSize.kt:23)
	at org.zimmob.zimlx.ZimPreferences$dockGridSizeDelegate$1.invoke(ZimPreferences.kt:94)
	at org.zimmob.zimlx.ZimPreferences$dockGridSizeDelegate$1.invoke(ZimPreferences.kt:32)
	at org.zimmob.zimlx.ZimPreferences$ResettableLazy.getValue(ZimPreferences.kt:595)
	at org.zimmob.zimlx.ZimPreferences.getDockGridSize(Unknown Source:8)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:328)
	at com.google.android.apps.nexuslauncher.NexusLauncherActivity.onCreate(NexusLauncherActivity.java:27)
	at org.zimmob.zimlx.ZimLauncher.onCreate(ZimLauncher.java:57)
	at android.app.Activity.performCreate(Activity.java:6984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2857)
	... 9 more
```

**Comment by lameventanas** [comment]
Me too.

**Comment by otakuhqz** [comment]
I will post in this thread a new compiled apk just for testing purposes and to check if the issue is resolved in the new versions.

**Comment by kalaleq** [comment]
Same issue here on a oneplus 3 running oxygenOS 9.0.3 (android 9), when updating 0.4.4 to 0.6.2b via f-droid. I get a fun crash screen with an upturned bug image. Had to un-install, then re-install 0.4.4.

Tried installing the 0.6.1 apk from github and it just tells me "App not installed".

Great launcher, i'm still using 0.4.4 after many years with Nova.  Would be happy to help test once the apk is available here.

**Comment by KaiMartin** [comment]
Same here on fairphone, google-less android 7.2.1: Immediate crash afzer update via f-droid.
I uninstalled zim 0.4. then installed zim 6.2. Got nothing in the list of backups. Had to reconfigure everything from scratch. But now zim is working fine.

**Comment by kalaleq** [comment]
Aha! Thanks KaiMartin for the hint. It must be something left over by 0.4.4 causing the crash after upgrade. I tried the same as you: uninstall, then re-install 0.6.2b from f-droid. Now it works.  I'll have to rebuild but worth it for the upgrade!

**Comment by mmm4m5m** [comment]
> I will post in this thread a new compiled apk just for testing purposes and to check if the issue is resolved in the new versions.

I have read that downgrading of non-debuggable packages is disabled. 
( Here - https://android.googlesource.com/platform/frameworks/base/+/921dd75 )
Uninstall is required and that will delete all the data files (settings) and cache files.

Currently the highest version (0.6.2b) is release package and downgrade (to 0.4.4) is NOT possible. Would you like to release a debuggable package with higher version (like 0.6.3)?
This way we can install the latest version - debuggable package. Then we can downgrade to version 0.4.4. 
This way we can preserve all data files and settings!

Thanks.
