### ISSUE TITLE
Cannot open: log attached

### ISSUE THREAD

**Issue by tycrek** [otakuhqz/ZimLX#54]
**Describe the bug**
Launcher fails to start. 

**To Reproduce**
Update from F-Droid and attempt to launch the app

**Expected behavior**
Launcher opens

**Smartphone (please complete the following information):**
 - Device: LG G7
 - OS: Android 9.0
 - Source: F-Droid

**Stack Trace**

```
Build version: 0.6.2b 
Build date: 1979-11-29 17:00:00 
Current date: 2019-06-19 17:01:51 
Device: LGE LM-G710 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.zimmob.zimlx/org.zimmob.zimlx.ZimLauncher}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2943)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3078)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6854)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:302)
	at org.zimmob.zimlx.ZimPreferences$IntPref.onGetValue(ZimPreferences.kt:452)
	at org.zimmob.zimlx.ZimPreferences$IntPref.onGetValue(ZimPreferences.kt:450)
	at org.zimmob.zimlx.ZimPreferences$PrefDelegate.getValue(ZimPreferences.kt:545)
	at org.zimmob.zimlx.settings.GridSize.getNumRowsPref(Unknown Source:7)
	at org.zimmob.zimlx.settings.GridSize.applyNumRows(GridSize.kt:31)
	at org.zimmob.zimlx.settings.GridSize.<init>(GridSize.kt:23)
	at org.zimmob.zimlx.ZimPreferences$dockGridSizeDelegate$1.invoke(ZimPreferences.kt:94)
	at org.zimmob.zimlx.ZimPreferences$dockGridSizeDelegate$1.invoke(ZimPreferences.kt:32)
	at org.zimmob.zimlx.ZimPreferences$ResettableLazy.getValue(ZimPreferences.kt:595)
	at org.zimmob.zimlx.ZimPreferences.getDockGridSize(Unknown Source:8)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:328)
	at com.google.android.apps.nexuslauncher.NexusLauncherActivity.onCreate(NexusLauncherActivity.java:27)
	at org.zimmob.zimlx.ZimLauncher.onCreate(ZimLauncher.java:57)
	at android.app.Activity.performCreate(Activity.java:7151)
	at android.app.Activity.performCreate(Activity.java:7142)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2923)
	... 11 more

```

**Comment by tycrek** [comment]
Closing as duplicate of #53
