### ISSUE TITLE
Crashed often e. G. restore 

### ISSUE THREAD

**Issue by Eddilein** [otakuhqz/ZimLX#56]
Crahed when I use the restore option. from Googledrive. 

Build version: 0.6.2b 
Build date: 1979-11-30 01:00:00 
Current date: 2019-07-06 12:21:14 
Device: Xiaomi MI 9 
 
Stack trace:  
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { dat=content://com.google.android.apps.docs.storage/document/acc=1;doc=encoded=JHdmEhRPNrbwZ//Bks6kfzGiVDfzc9nkuJH44F822+ViThMOiiIFxmT8c7BGBU+T flg=0x43 }} to activity {org.zimmob.zimlx/org.zimmob.zimlx.backup.BackupListActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4423)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4465)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6815)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at org.zimmob.zimlx.backup.BackupListAdapter.get(BackupListAdapter.kt:51)
	at org.zimmob.zimlx.backup.BackupListActivity.openRestore(BackupListActivity.kt:90)
	at org.zimmob.zimlx.backup.BackupListActivity.onActivityResult(BackupListActivity.kt:173)
	at android.app.Activity.dispatchActivityResult(Activity.java:7590)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4416)
	... 11 more
 clear and concise description of what the bug is.

![Screenshot_2019-07-06-12-24-24-818_org zimmob zimlx](https://user-images.githubusercontent.com/52598156/60754963-29438d00-9fe9-11e9-971b-3884442463ce.png)
![Screenshot_2019-07-06-12-26-40-069_com android settings](https://user-images.githubusercontent.com/52598156/60754974-5728d180-9fe9-11e9-933f-72778f976abe.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by otakuhqz** [comment]
Fixed on v0.6.3
