### ISSUE TITLE
Launcher crashes when home screen tries to rotate to landscape

### ISSUE THREAD

**Issue by michaelgray2020** [otakuhqz/ZimLX#67]
When I turn on rotation and turn my phone to landscape, the launcher crashes. Doesn't matter what settings in either launcher or my OS, it always crashes. 

Build version: 0.6.2b 
Build date: 1979-11-29 18:00:00 
Current date: 2019-09-29 22:29:37 
Device: OnePlus ONEPLUS A6013 
 
Stack trace:  
java.lang.ClassCastException: androidx.drawerlayout.widget.DrawerLayout cannot be cast to com.android.launcher3.LauncherRootView
	at com.android.launcher3.Launcher.getRootView(Launcher.java:1339)
	at com.android.launcher3.Launcher.reapplyUi(Launcher.java:536)
	at com.android.launcher3.Launcher.onConfigurationChanged(Launcher.java:522)
	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:5166)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5033)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5011)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5374)
	at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:43)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Smartphone
 - Device: OnePlus 6T
 - OS: OxygenOS 9.0.15
 - Browser Chrome
 - Version 77.0.3

**Comment by omgwtfbbqpls** [comment]
Same issue:
```

Build version: 0.6.2b 
Build date: 1979-11-30 02:00:00 
Current date: 2019-11-18 21:07:45 
Device: Motorola Moto X4 
 
Stack trace:  
java.lang.ClassCastException: androidx.drawerlayout.widget.DrawerLayout cannot be cast to com.android.launcher3.LauncherRootView
	at com.android.launcher3.Launcher.getRootView(Launcher.java:1339)
	at com.android.launcher3.Launcher.reapplyUi(Launcher.java:536)
	at com.android.launcher3.Launcher.onConfigurationChanged(Launcher.java:522)
	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:5069)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:4936)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:4914)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5287)
	at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:43)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Device: Moto X4
OS: LineageOS 16 for MicroG 

The widgets on my desktop are from Poweramp, and the ones from the "Your local weather" app on F-Droid.

**Comment by ka223** [comment]
Seems to the same problem I posted here: https://github.com/otakuhqz/ZimLX/issues/62

**Comment by otakuhqz** [comment]
I just upload the current build apk in the issue #26. it is fixed in the current build
