### ISSUE TITLE
frequently crashes when envoked

### ISSUE THREAD

**Issue by mynameisflorian** [otakuhqz/ZimLX#82]
**Describe the bug**

Application frequently (but not always) crashing when envoked 

**To Reproduce**

Press the home button while in another app.

Build version: 0.6.2b 
Build date: 1980-01-01 00:00:00 
Current date: 2020-04-22 13:52:07 
Device: Motorola Moto E (4) 
 
Stack trace:  
java.lang.NoSuchMethodError: No virtual method canShowBadge()Z in class Landroid/service/notification/NotificationListenerService$Ranking; or its super classes (declaration of 'android.service.notification.NotificationListenerService$Ranking' appears in /system/framework/framework.jar)
	at com.android.launcher3.notification.NotificationListener.shouldBeFilteredOut(NotificationListener.java:378)
	at com.android.launcher3.notification.NotificationListener.filterNotifications(NotificationListener.java:358)
	at com.android.launcher3.notification.NotificationListener.access$200(NotificationListener.java:56)
	at com.android.launcher3.notification.NotificationListener$1.handleMessage(NotificationListener.java:103)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Motorola Moto E (4) 
 - OS: Android 7.1.1

**Additional context**

**Comment by otakuhqz** [comment]
I have been having some problems with the notifications in android 7.1 and lower versions.
what you can make is disable the notifications by clicking the setting button in the apps setting menu.
there is a new pre-release in the telegram channel, but a lot of features are missing, since I'm making a migration to android 10.
